apiVersion: v1 # Версия API
kind: Pod # Объект, который создаем
metadata:
 name: myweb
 labels: # Метки в формате key: value
   app: web
spec: # Описание Pod
 containers: # Описание контейнеров внутри Pod
 - name: web
   image: 2kw92/homework_docker:homework_v1
   readinessProbe: # Добавим проверку готовности
     httpGet: # веб-сервера отдавать
       path: /index.html # контент
       port: 80
   livenessProbe:
      tcpSocket:
        port: 8000
