expose:
  type: ingress
  ingress:
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
      cert-manager.io/issuer: "letsencrypt-production"
      cert-manager.io/acme-challenge-type: http01
    hosts:
      core: harbor.84.201.171.144.sslip.io
  tls:
    secret:
      secretName: letsencrypt-cert
externalURL: https://harbor.84.201.171.144.sslip.io
notary:
  enabled: false