apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    email: 2kw92@mail.ru
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
    - http01:
        ingress:
          class: nginx

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-cert
spec:
  secretName: letsencrypt-cert
  issuerRef:
    kind: Issuer
    name: letsencrypt-production
  commonName: harbor.84.201.171.144.sslip.io
  dnsNames:
  - harbor.84.201.171.144.sslip.io