apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: frontend
  name: frontend
spec:
  containers:
  - image: 2kw92/frontend:0.1
    name: frontend
    env:
    - name: PRODUCT_CATALOG_SERVICE_ADDR
      value: "192.168.1.1"
    - name: CURRENCY_SERVICE_ADDR
      value: "192.168.1.2"
    - name: CART_SERVICE_ADDR
      value: "192.168.1.3"
    - name: RECOMMENDATION_SERVICE_ADDR
      value: "192.168.1.4"
    - name: CHECKOUT_SERVICE_ADDR
      value: "192.168.1.5"
    - name: SHIPPING_SERVICE_ADDR
      value: "192.168.1.6"
    - name: AD_SERVICE_ADDR
      value: "192.168.1.7"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}

