apiVersion: v1
kind: Pod
metadata:
  name: myweb
  labels:
    app: web
spec:
  initContainers:
    - name: initweb
      image: busybox:1.31.0
      command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
      volumeMounts:
        - name: app
          mountPath: /app

  containers:
  - name: web
    image: 2kw92/homework_docker:homework_v1
    volumeMounts:
      - name: app
        mountPath: /app
  volumes:
    - name: app
      emptyDir: {}
